### ISSUE TITLE
Attack function simply does not work.

### ISSUE THREAD

**Issue by Trisscar05** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#1003]
**Describe the bug**
Magic missile worked just fine, but anytime anyone tried to use the "attack" animation, it loaded for about a minute and then stopped, while not playing any animations that might have been tied to it.

**Additional context**
Looking at some of the reports here it may just be disabled atm tbf. *shrug*

**Comment by LuPro** [comment]
Did you try the attack action while being a player? If so that generates a request for the GM and they have to "accept" the attack first. Magic missile is bugged right now and ignores this request unfortunately and the "waiting for GM" request thing looks like a loading circle if you don't know what it means which is why it sounds to me like this

**Comment by Trisscar05** [comment]
I was a player at the time yes, I'll have to query the DM during the next game to see if that comes up.

**Comment by LuPro** [comment]
In that case I'll close this issue - if you can get it replicated with the DM saying there's been no request please do tell in that case I'll of course reopen the issue :)

**Comment by Trisscar05** [comment]
Nah requests were working. I'll say this though cause the entire group was saying it unprompted; the Magic Missile function is incredibly useful both for bored players waiting their turn, and to indicate exactly which model you want to attack in a way that doesn't require using the ruler tools, which can be a bit inaccurate for this particular use. I think it should be kept this way frankly.
