### ISSUE TITLE
Paste Slab Produces Heart Emoji

### ISSUE THREAD

**Issue by USMCM1A1** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#233]
**Describe the bug**
I can CTR+C copy a slab, and in game CTR+V paste it fine.  However when I try and paste it into a web-browser, note pad, etc., this emoji appears: ❤

**To Reproduce**
1. Copy slab via CTR+C
2. Paste in game CTR+V
3. Tried to paste in another application
4. Get ❤

**Additional context**
Windows 10

**Comment by LuPro** [comment]
While cleaning up old issues I realized I never came around to answering to this: this is expected behavior and happens when you copy a slab that is too large to be copied outside (exceeds the 30kB limit), but it still can be copied in the game (for technical reasons you can copy larger things if you don't leave TS than if you do "go outside of TS")
