### ISSUE TITLE
No UI Showing Up

### ISSUE THREAD

**Issue by Zandria721** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#274]
**Describe the bug**
Two things did not happen
1) I could not rotate any walls (possibly items as well, I did not test those)
2) When I intered into the campaign, no UI showed up on screen

**To Reproduce**
1. Computer died while game was open
2. Plug computer in and turn it back on (TaleSpire still up)
3. Try to continue building dungeon and be unable to rotate the walls
4. Close the campaign
5. Re-open the campaign
6. No UI shows up even after hitting the Space Key

**Screenshots/Videos/Twitch Clips**

![TaleSpire](https://user-images.githubusercontent.com/63561080/79079066-b46d5400-7cda-11ea-834d-a35b7b4c8fed.png)

**Comment by LuPro** [comment]
it looks like you have encountered #5 - you have the board and campaign menu in the top left still, but not build menu and dice. What probably happened is that you had a board with stuff on it, then as your computer (I presume laptop and low battery?) died it lost connection or triggered some other bug and when you rejoined (from hibernation I assume?) it couldn't reconnect properly.
Then either due to the crash/improper reconnect or due to one of the sync/persistence bugs the board got stored as an empty board. If that happens, TaleSpire automatically removes it (so that there isn't unnecessary clutter in the board list, any empty ones will be removed) then you rejoined the campaign and you didn't have any board to join, so you got the "no board screen" which is what is described in the issue I linked.

Could you confirm if making a new board fixed this? If so it's most likely a duplicate and not a new bug

**Comment by BlinkstarPB** [comment]
I just had a similar issue when loading into a campaign. No U.I. except the Cog, Question, and Exit. I clicked a bit around the W.S.A.D area and the left buttons came up. After clicking on the campaign button and loading the same board everything came back up. Previous instance did not crash, and no power loss. Let me know if you need anything.

**Comment by Zandria721** [comment]
I didnt know I could make a new board (my first time playing and I was experimenting). I made a new campaign and didnt have that issue. Thank you for the information!
