### ISSUE TITLE
Unable to re-order Boards

### ISSUE THREAD

**Issue by yaccin** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#292]
**Describe the bug**
I want to arrange the boards in a different order, but there is no way to do that.

**To Reproduce**
1. create a few boards
2. be unhappy about the order of the boards
3. try to reorder the boards in a more logical manner 

**Screenshots/Videos/Twitch Clips**
no screenshots required

**Additional context**
Additional context may be unlocked for a one-time payment of $1.99

**Comment by LuPro** [comment]
While cleaning up old issues I noticed I never got around to answering this one:
Boards are sorted alphabetically, so that's intended behavior to not be able to reorder them. However especially if you get more and more boards this is getting cumbersome so there will probably be an overhaul of the board list at some point in the future, there's no ETA on that though. I'll close this as it's not a bug.
