### ISSUE TITLE
Can't Rotate Tiles

### ISSUE THREAD

**Issue by Tuffghost89** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#315]
**Describe the bug**
No matter what I do I can't reliably rotate tiles.

**To Reproduce**
I have tried lifting the mouse off the table so it doesn't register movement, but only 1 in maybe 50 clicks will actually rotate the tiles I am using, which obviously makes the program unusable :(
I have tried using other mice, but nothing seems to work.

**Screenshots/Videos/Twitch Clips**
These are worth their weight in gold!

**Additional context**
Unburden yourself of thoughts and musings here

**Comment by samoht21** [comment]
I have had this experience. I adjusted my mouse setting and slowed the action of the wheel mouse and it helped a bit. I also disabled horizontal scrolling (I don't know if that helped at all). 
I noticed that it helped it when I press the wheel mouse button and hold it for a half second before releasing it, and that helped it to register the action better.

**Comment by LuPro** [comment]
Try clicking a bit "longer", not necessarily holding, but press with "more intent" if you understand what I mean. Some of the inputs sometimes take a while to react for some reason and clicks that are too fast might go by unseen by the game (see #13, which would be related to that). Could you tell me if that works better for you?

**Comment by Tuffghost89** [comment]
I have tried. I loaded up the game again the next day and it seemed to work
more or less fine but over the next 15 minutes it gradually became harder
to rotate. Almost like it just gradually lost the ability to sense the
difference between zooming or rotating. Tried different mice. Still wasnt
working.

**Comment by Oldman-M** [comment]
I'm having this issue as well. To get around it I have to flick my mouse as I middle mouse click. It rotates the map a bit as I do it as well, but that's the only way that I can reliably get the asset/tile to rotate. I'm guessing that since holding down the middle mouse is also bound to rotating the map that there's a conflict going on & the code is getting confused on what it should do.

**Comment by LuPro** [comment]
With the chimera release 2 days ago the rotation system has been overhauled (rotation is now holding alt and moving mouse in the direction you want to rotate to, similar to how mini rotation works) - so hopefully whatever that issue was if it didn't get fixed for you now it should definitely not be a problem anymore :)
