### ISSUE TITLE
Middle Mouse Button does not register

### ISSUE THREAD

**Issue by Lukeal4814** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#346]
**Describe the bug**
Clicking the middle mouse button does nothing in any area it is supposed to.
It does not rotate the camera when using the mouse. Q and E do woerk
It does not rotate an item when selected.
I have tried to click forcefully and slowly and adjusted the sensitivity to one line and from 800 to 16000 on the overall mouse. Also in the mouse normal settings.
Mouse is a Razer Naga Hex V2 and the button is set to default (Scroll Click)

**To Reproduce**
1) move camera
2) presss and hold middle mouse (clear click and select)
3) board does not rotate. Use Q and E does rotate
1) select object to place
2) click middle mouse. nothing at all happens. click and hold. nothing. click like mad, nothing
3) cannot rotate object as far as I can see on the keyboard shortcuts (Q and E do not work here, but should they?)

**Screenshots/Videos/Twitch Clips**
Not really possible or useful.

**Additional context**
as long as all my corners are only on one side, I can build stuff :)

**Comment by TheRealNiall** [comment]
I have the exact same Issue.
Possible solution would be enabling rebinding keys

**Comment by The-Shepherd676** [comment]
Ran into the same issue, but oddly enough I also can't place token pieces or middle-click on any existing ones either.

**Comment by pocketaimee** [comment]
Same unable to use the middle mouse button in the game.

**Comment by Jerekoburn** [comment]
The middle mouse button registering has been a chronic issue since beta release. Currently it works if I click on it like 7 or 8 times. It's making building extremely difficult.

**Comment by Mormonkniv** [comment]
Same here, impossible to build like this. I find that rotating blocks is a pretty important part of map building! Enabling key binding changes would be great. I don't need WASD to do the same things as my arrow keys, it would be great if I could change one set or the other to rotate objects.

**Comment by LuPro** [comment]
While cleaning up old issues I found this one again, and there's been some development on this front:
I don't think the root cause has been found for this as some people would have this issue while others are completely unable to reproduce it (including the devs), in any case there is now key rebinding available so if middle mouse button doesn't work for you, you should be able to change the keybinds. The key rebinds are fairly new and not all functions have been added yet, but I think the middle mouse button functions are currently rebindable already.
I'll close this issue because apart from a few functions (duplicating tiles, rotating camera) all of which can be achieved with other keys as well this is a non-issue anymore (tile rotation is done with alt + mouse drag now), however it would still be interesting to find out why for some people it's almost impossible to use middle mouse button while for most others there's no issue.
