### ISSUE TITLE
Right side menu disappears after deleting active board

### ISSUE THREAD

**Issue by Dahlgren** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#5]
**Describe the bug**
Right side menu disappears when current board is deleted 

**To Reproduce**
1. Create a new board
2. Open Boards menu
3. Delete active board
4. Right side menu disappears
5. Exit to main menu
6. Open the same campaign (and board)
7. Right side menu is back

**Screenshots/Videos/Twitch Clips**
https://youtu.be/PfSsmvKN4EQ

**Additional context**

**Comment by Sebdevar** [comment]
Hi, I don't think that is a bug, considering you are no longer in a board, I think it's voluntary for you to be unable to build until you enter another board.

As for how to approach this issue in terms of user experience, I'd suggest opening the board menu and offering a clear message to the user on how they should select a board to continue building.

**Comment by LuPro** [comment]
From what I could see in the description (and the video, super helpful that one) it looks like intended behavior:
When you delete the board you are on, the right side menu disappears because you cannot use it anyways - no board, no placement of tiles. If you would go back to the old board (Unknown Realm 1) the right side menu would appear again.
The menu is also back on exiting to menu and going back, because the old board (Unknown Realm 1) that was not deleted is set as default, so instead of loading into "no board" (which you were "in" when you deleted and then exited to menu) it loads to the default board (Unknown Realm 1) and thus shows the right menu again.

What might be a viable enhancement idea though is automatically loading into a board (the default board?) when you delete the board you are on (if there are other boards to load to of course)

**Comment by LuPro** [comment]
Check issue #19, idea to resolve this misunderstanding is discussed there

**Comment by AnarchyFive** [comment]
seeing this as well. the right side menu is gone, but so is the abiility to go back to your other boards or realms

**Comment by LuPro** [comment]
@AnarchyFive could you elaborate on that? All instances of this issue I've seen so far have been with confusing UI and the menus not showing, once explained people could get back to their boards, but if there's some other bug preventing you from switching back to the other boards or making new ones that should be logged.
