### ISSUE TITLE
visible layer doesn't change at full zoom

### ISSUE THREAD

**Issue by Benjaneer** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#508]
**Describe the bug**
Here tell us what you thought was meant to happen and then how TaleSpire vomited on itself

**To Reproduce**
1. build something
2. zoom out full
3. move visibility slider down
4. everything is still visible

**Screenshots/Videos/Twitch Clips**
These are worth their weight in gold!

**Additional context**
The mouse wheel zoom drives me crazy, I have to use the middle button to rotate items and camera so it eventually turns by accident and takes several minutes to get the zoom to anywhere between either full out or full in.

**Comment by LuPro** [comment]
Not a bug, but intended behavior - worth a discussion on the discord whether that should be the case or not though.

Regarding the "full out or full in", as this is an older report this might already have been fixed, as behavior like this was mostly seen on with low framerates and an update since then fixed some poor player controller/camera behavior while at low framerates - is this also the case for you, or is it still occuring (if it is still occuring put that in a new issue please)
