### ISSUE TITLE
Pressing N makes a 10x10 Chunk of Tiles Turn Invisible

### ISSUE THREAD

**Issue by swyndelinewriter** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#513]
**Describe the bug**
While in build mode and working on a large project I will use the cutbox to copy sections. To improve workflow I try to use the keyboard shortcuts but when I press N a 10x10 chunk of tiles turns invisible. Moving the camera moves the hole and the missing tiles reappear. Also, an orange box is offset from the 5th quick use tile box from the right side. 
![TS Bug 1 After Pressing N](https://user-images.githubusercontent.com/64670468/80891325-1f75cf00-8c78-11ea-8438-00c147da132d.PNG)
![TS Bug 1 Before Pressing N](https://user-images.githubusercontent.com/64670468/80891329-213f9280-8c78-11ea-8dc2-584bdccae3be.PNG)

Pressing N again removes the issue, but it comes back when you press N. Using the mouse to select the cutbox tool from the tool menu brings up the cutbox normally.

**To Reproduce**
1. Press N after working for an hour on a large board
2. 10x10 section of tiles turns invisible
3. Pressing N brings them back
4. Selecting the cutbox from the menu brings up the tool normally

**Screenshots/Videos/Twitch Clips**
These are worth their weight in gold!

**Additional context**
Unburden yourself of thoughts and musings here

**Comment by PanoramicPanda** [comment]
It's a little hard to see due to your resolution (so I'd classify this as a UI issue), but that orange box is the "Cutbox" tool (and is a black box w/icon when not on) - it makes a roughly 10x10 section see through to aid with building/seeing things beneath other tiles.

Perhaps the cutbox from the toolbar you're referring too is the Volumetric Selection tool?
