### ISSUE TITLE
Startup

### ISSUE THREAD

**Issue by Bunnybuttuwu** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#539]
Cant even launch Talespire. At first the program only crashed when copying and pasting tiles, and i thought everyone had that issue at launch. I've tried reinstalling, and the bugs only got worse.
Feel like i wasted my money on something that doesnt work.

**Comment by LuPro** [comment]
Is it possible that you have a rather old AMD Phenom CPU? If so, it could be related to issue #7 or by extension #87. If it is the case that you have this CPU, then there's nothing you can do for now because some of the Unity libraries used in the game don't support this CPU (or actually the other way around, those CPUs don't support certain features that tool needs. The devs have worked on this and a newer version of this tool should fix this, but it is not in a stable release version and thus has a bunch of bugs that the devs have to wait for the maintainers of this to get it fixed, it's out of their hands unfortunately.

If your CPU is not one of those (or generally a CPU from this era, there have been reports from Intel CPUs of this age) then please check your game logs which might have further information that could help the devs fix this. You can find the logs in C:\Users<YOURUSERNAME>\AppData\LocalLow\BouncyRock Entertainment\TaleSpire\Player.log and Player-prev.log. Alternatively if you can get into the game you could try to open the dev console by triple clicking in the top left corner of the game, this should also show any error messages (though the log files are probably more helpful as they show the previous errors as well).
Please keep in mind that this is an early beta version, bugs are to be expected, but the devs are working very hard to get it working for everyone :)

**Comment by LuPro** [comment]
I will close this as there isn't enough information/any follow up. If this is still occurring please do comment with more details, otherwise it's not really possible to diagnose/fix.
