### ISSUE TITLE
Object clipping when zooming in on multi layered design

### ISSUE THREAD

**Issue by Sergueil819** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#546]
When building over multiple levels ( Castle with 15floors for example ) and going back to set your camera on the lowest floors, the highest floors will start blocking your view when trying to look around. It's as if the area hidden from view (with the green eye icon) had a max width.

The problem does not appear until you build something wide and high enough. The current building I'm working on which displays the problem is 70x70x70 tiles (Using simple 1x1 floor tiles to calculate).

![Bug report 1](https://user-images.githubusercontent.com/65605066/82329371-38d48600-99af-11ea-9879-49baa0df2ad9.png)

**Comment by LuPro** [comment]
Sounds like a duplicate to #543 to me (and I think some issues before that, but I can't find them right now). The issue seems to be that the cutaway doesn't remove in a large enough area/doesn't move the removed tiles high enough. Could you confirm that the description in #543 matches your issue? If not, please clarify what's different :)

**Comment by Sergueil819** [comment]
Wow, thanks for the fast response! 

Yes, the issue seems to be the same. From what I read from post #543, the problem is encountered under the same circonstances.

Thank you very much and Congratulations on creating something this awesome!

**Comment by LuPro** [comment]
I'll close this issue then - check the other for updates to see when things resolve :)
