### ISSUE TITLE
Usability issues

### ISSUE THREAD

**Issue by subgenius** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#579]
There seems to be a point where I can't zoom out any further and from a build standpoint that is very frustrating. I imagine for players it maybe frustrating as well. 

Also it would be great if there was some build tutorial in the final version. I am struggling with what I would consider to be basic functionality. Like shortcuts for rotating a character/terrain. Maybe something like a we're going to build a house and then it instructs you on how to turn pieces, etc.

**Comment by LuPro** [comment]
Making a tutorial for the current state of the game is pretty much a waste of time because both default keybindings, as well as available tools will change a *lot*. I am positive that there will be a tutorial once the game matures more. in the meantime there are some tutorials available on YouTube (if you're in the discord, check out #faq, they should be there).
As for the camera, the devs are working on updating the tooling and that includes the camera, they are aware it's not perfect right now. whether that will entail being able to zoom out more is not really known right now because there's a lot of things that impact this (most obvious: performance). As this is more a feature request than anything I'll close this issue here, you can go into the discord and discuss there in more depth if you so wish :)
