### ISSUE TITLE
Atmosphere reset bug

### ISSUE THREAD

**Issue by KingofCastamere** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#752]
**Describe the bug**
Here tell us what you thought was meant to happen and then how TaleSpire vomited on itself

When I closed camera mode, the atmosphere settings of my world reset.

**To Reproduce**

1. Change sunlight settings from default
2. Open Camera Mode
3.  Close Camer Mode
4. Atmosphere settings reset to default

**Screenshots/Videos/Twitch Clips**
These are worth their weight in gold!

**Additional context**
Unburden yourself of thoughts and musings here

**Comment by LuPro** [comment]
Changing the atmosphere settings is actually just a "preview", you have to press "apply to board" at the bottom for them to actually be applied (and visible to the players). That way you can make changes and your players will only see the final result and not the mucking about in between. When going to photo mode and back it will use the atmosphere settings the board is set to (so not the ones you "previewed" because the photo mode has its own set of (independent) atmosphere settings). So you should just need to apply the atmosphere settings to the board and then you should be able to switch in and out of photo mode as you wish :)
Gonna close this as this doesn't sound like a bug, if I was misunderstanding something or the issue persists, please do comment so we can look into this a bit more
