### ISSUE TITLE
Snapping issues with stone walls

### ISSUE THREAD

**Issue by SaltDensity** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#78]
**Describe the bug**
So I was playing around with the mapmaking tool and I've come a cross some issues where if I put down a new line of tiles, the objects on them will not really line up with other objects. The objects specifically in question are the "stone wall" objects under the "nature" tab. 

**To Reproduce**
1. Lay tiles
2. Line up some stone walls
3. lay another row of tiles
4. The stone walls won't snap together

I tried using the clipping tool to fix it, but the walls just clip into the ground but still snap to the grid. 

**Screenshots/Videos/Twitch Clips**
[Step 1
](https://i.imgur.com/AFtoWRw.jpg) - create pumpkin patch and tiles
[Step 2](https://i.imgur.com/IVC4Doi.jpg) - try to place wall
[Step 3](https://i.imgur.com/aXygiol.jpg) - watch the wall fail to snap to the stone corner no matter how hard you try

[Bonus](https://i.imgur.com/ZbRHmns.jpg) - this wall has an inexplicable gap

**Additional context**
PLEASE let us disable grid snapping!!

**Comment by SaltDensity** [comment]
Ok so I found with further testing this problem is specifically to do with "stone wall corner 2" - stone wall corner 1 works fine, HOWEVER stone wall corner 1 still has that inexplicable gap when connecting to the other stone walls.

I still reserve my comment about needing to let us disable grid snapping

**Comment by LuPro** [comment]
It seems that the error could be similar to #17 - unfortunately not on PC to confirm that right now, if not I suspect it is an asset issue similar to #48 .

That said, grid snapping (for tiles) is here to stay, it has to be due to code simplicity and especially performance. props are planned to get a finer grid than now. The gap is intended though (they are going for a "physical tile" aesthetic) - at least for the straight walls. it seems the corner wall and straight wall have a larger gap than they should have, I'll tag that as an asset issue.

**Comment by Maxnwil** [comment]
> That said, grid snapping (for tiles) is here to stay, it has to be due to code simplicity and especially performance. props are planned to get a finer grid than now. The gap is intended though (they are going for a "physical tile" aesthetic) - at least for the straight walls. it seems the corner wall and straight wall have a larger gap than they should have, I'll tag that as an asset issue.

Grid snapping makes a lot of sense, but a finer grid would be most excellent. Furthermore, it would be great if we could manually nudge objects. Right now, even with clipping "on", it's very difficult to, for instance, put a table in a corner (as the wall corner object takes up a 2x2 zone). Being able to nudge an asset +1 grid spacing by pressing a key command would be of great use in fixing these issues.

**Comment by LuPro** [comment]
Props (like tables) will receive a different system to place them on a finer grid with more rotation options (not completely free placement, but close to it), this is already in the works, just not quite finished. In the future there will be a large distinction between props and tiles in the way they are placed and used in the game. Tiles will not have any changes to their grid or grid spacing, props are already in the works to get a finer grid of 3x3 attachment slots per grid square (might be wrong with that number but somewhere in that ballpark) and 16 rotation angles.

**Comment by Maxnwil** [comment]
> Props (like tables) will receive a different system to place them on a finer grid with more rotation options (not completely free placement, but close to it), this is already in the works, just not quite finished. In the future there will be a large distinction between props and tiles in the way they are placed and used in the game.

Is this why Fences are props? So that they can be placed closer to edges and such?

> Tiles will not have any changes to their grid or grid spacing, 

This is _mostly_ fine, but I do worry about some issues there; namely, will there be more fine-control on stairs? Right now 2 stair blocks = 1 wall height, which means there's always a floor height of offset at the top of a 2 block high stair. Is that not seen as a concern?

Hopefully that made sense!

**Comment by LuPro** [comment]
As I see it now, stairs are a giant steaming pile of... well, you know. They don't really build intuitively and always feel like a hack that's not supposed to work when using it to me. Of course any of the things I said *could* change when the devs find out that it is needed (though the thing about tiles staying on the current grid would surprise me a lot if it changed). The way I see it, stairs need a rework, how exactly that will look like is not really known as of yet - but they definitely won't become props because props will "dodge out of the way of the player" in the new prop system (so they don't take up too much space, there's a gif of that new system floating around somewhere, but I can't find it for the life of me).

As a small ps: I am not a dev myself, I'm just some crazy community member who is stupid enough to do work for the devs on his free time without payment :P What people do for their passion

**Comment by LuPro** [comment]
Prop system is here! 🎉 time to close this dinosaur of an issue :P
