### ISSUE TITLE
Tiles float off into the sky with mousewheel zoom

### ISSUE THREAD

**Issue by brockodle** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#795]
Name | about | title | labels | assignees
-- | -- | -- | -- | --
Tiles float away | Suddenly the tiles floated away after placing some rocks |   |   |  

To Reproduce Steps to reproduce the behavior:

1. building a gangplank in a relatively low water level
2. making rocks to connect to an upper landing with cobblestone floor
3. after placing a few rocks, the tiles of cobblestone disappear, but shadows remain, animate as if flying into the sky.
4. can't fix yet, re-loading the map doesn't help, best I can gather it has to do with camera distance from the tiles! hope the video below helps!

https://www.youtube.com/watch?v=No6sCIDl5oQ

GREAT WORK EVERYONE! This will be an amazing tool and I can't wait to see where it goes!

**Comment by LuPro** [comment]
You're "encountering" the green cutoff slider to the right - that's a feature to hide tiles above a certain height to be able to look into building and below roofs and the like. It does not apply on the furthest zoom levels, which is why you see everything when completely zoomed out. try building a tower, zooming in a bit and moving the green slider up and down to get a feel for it. 

PS: sometimes there's a bug where even when the slider is at the top (where it shouldn't cut off anything) it still does cut off things, just move it around a bit and then that gets fixed. what happened for you probably is on double right click there's a refocus and this automatically moves the green slider to hide anything above what you double right clicked on if it is obstructed (similar feature for mini movement) so you're able to see what you focused on.

So it's not a bug, but a bit badly communicated feature :)

**Comment by brockodle** [comment]
Aha! That's actually clever now that I know haha. Would be useful for multi level. :) Thanks!
