### ISSUE TITLE
Fail to assign a player whit an internal id

### ISSUE THREAD

**Issue by SeaBorn2257** [Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker#88]
When trying to join a friends campian, i get an error message that tells me that 

1. friends was not able to make a invite link. 
2. Left the campaign and rejoins 
3. a lot of work was not saved. but was now able to send a link
4. after joining and my friend giving me the gm status, i am then just getting the "preparing for adventure" were it eventually will tell me that it can fetch the board and just having me on "preparing for adventure" were it just loads.
5. after leaving and  i join and get an error message

[https://imgur.com/a/5vasIDk](url)

**Comment by creadth** [comment]
Same occured for me

**Comment by cbaggers** [comment]
relinking image as github did something weird to it https://imgur.com/a/5vasIDk

**Comment by cbaggers** [comment]
Thanks for the report. I think we are seeing a combination of two errors.

The first is that, before Tuesday we had an error where the backend would lose information about sessions (ongoing games) as so would not know that your friend was a valid player. Because of this they were not allowed to send you the board.

The second is, I believe, unresolved and so I will look into this next.

**Comment by cbaggers** [comment]
I am going to spin the shader id off as it's own ticket

**Comment by LuPro** [comment]
As these issues haven't been encountered in quite a while and quite a lot of issues regarding persistence have been fixed since a while already, I'll close this. If any issues regarding this pop up again, please create a new issue
